version: '3.8' # Specify compose file version

services:
  postgres:
    image: postgres:15 # Use PostgreSQL version 15
    container_name: knowledge-cards-db # Name the container
    environment:
      POSTGRES_USER: user # Default username from .env
      POSTGRES_PASSWORD: password # Default password from .env
      POSTGRES_DB: knowledge_cards # Default database name from .env
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data using a named volume
    restart: always # Always restart the container if it stops

volumes:
  postgres_data: # Define the named volume 