from typing import Optional, List, Any, Dict
from pydantic import BaseModel, Field
from datetime import datetime

class RawImageInput(BaseModel):
    image_id: str = Field(..., description="Unique ID for the image within this processing job, generated by acquisition service.")
    image_bytes: Optional[bytes] = Field(None, description="Raw bytes of the image.")
    source_url: Optional[str] = Field(None, description="URL if the image is from the web and not yet downloaded, or for reference.")
    original_filename: Optional[str] = Field(None, description="Original filename if applicable.")
    source_document_id: str = Field(..., description="Identifier for the source document (e.g., URL, file path, job_id).")
    page_number: Optional[int] = Field(None, description="Page number in the original document where the image was found.")
    bbox: Optional[List[float]] = Field(None, description="Bounding box [x0, y0, x1, y1] of the image on its page.")
    mime_type: Optional[str] = Field(None, description="MIME type of the image, if known.")
    alt_text: Optional[str] = Field(None, description="Extracted alt text from acquisition, if any.")
    caption: Optional[str] = Field(None, description="Extracted caption from acquisition, if any.")
    original_source_identifier_for_gcs_path: str
    source_type_for_gcs_path: str
    job_id_for_gcs_path: str

class EnrichedImageMetadata(BaseModel):
    image_id: str = Field(..., description="Corresponds to RawImageInput.image_id.")
    gcs_url: Optional[str] = Field(None, description="URL of the image stored in GCS.")
    alt_text: Optional[str] = Field(None, description="Original or LLM-refined alt text.")
    caption: Optional[str] = Field(None, description="Original or LLM-refined caption.")
    llm_description: Optional[str] = Field(None, description="LLM-generated description of the image content.")
    width: Optional[int] = Field(None, description="Image width in pixels.")
    height: Optional[int] = Field(None, description="Image height in pixels.")
    original_source_identifier: str = Field(..., description="Matches RawImageInput.original_source_identifier_for_gcs_path for linking.")

class PreliminaryBlock(BaseModel):
    block_id: str = Field(..., description="Unique ID for this block within the document.")
    type: str = Field(..., description="Type of content (e.g., 'text', 'heading', 'list_item', 'image_placeholder', 'code_snippet', 'math_text', 'table_placeholder').")
    text_content: Optional[str] = Field(None, description="Text for 'text', 'heading', 'list_item', 'math_text'.")
    image_id_ref: Optional[str] = Field(None, description="Reference to RawImageInput.image_id for 'image_placeholder'.")
    code_content: Optional[str] = Field(None, description="Code for 'code_snippet'.")
    code_language: Optional[str] = Field(None, description="Language for 'code_snippet'.")
    heading_level: Optional[int] = Field(None, description="Level (1-6) for 'heading'.")
    list_item_data: Optional[Any] = Field(None, description="Content of the list item (e.g. string, or more structured data for complex items).")
    list_level: Optional[int] = Field(default=0, description="Indentation level for 'list_item'.")
    list_ordered: Optional[bool] = Field(None, description="True if 'list_item' belongs to an ordered list.")
    page_number: Optional[int] = Field(None, description="Page number in the original document.")
    bbox: Optional[List[float]] = Field(None, description="Bounding box [x0, y0, x1, y1] on the page.")
    order: int = Field(..., description="Sequential order of the block in the document flow.")
    custom_attributes: Optional[Dict[str, Any]] = Field(default_factory=dict, description="For any other extracted attributes, e.g., style info, table HTML.")

class DocumentMetadata(BaseModel):
    document_id: str = Field(..., description="Unique ID for this processed document instance (e.g., job_id).")
    source_identifier: str = Field(..., description="Original filename, URL, etc.")
    source_type: str = Field(..., description="Type of source (e.g., 'pdf', 'docx', 'url', 'txt', 'md').")
    final_url: Optional[str] = Field(None, description="Final URL after any redirects (for web sources).")
    title: Optional[str] = Field(None, description="Extracted document title.")
    author: Optional[str] = Field(None, description="Extracted document author(s).")
    subject: Optional[str] = Field(None, description="Extracted document subject.")
    keywords: Optional[List[str]] = Field(default_factory=list, description="Extracted keywords.")
    creation_date: Optional[datetime] = Field(None)
    modification_date: Optional[datetime] = Field(None)
    extracted_at: datetime = Field(default_factory=datetime.utcnow)
    total_pages: Optional[int] = Field(None)
    language_detected: Optional[str] = Field(None, description="Detected language of the content.")
    custom_fields: Optional[Dict[str, Any]] = Field(default_factory=dict) 