#!/usr/bin/env python
# coding: utf-8
"""
Defines Pydantic models for specific task outputs within crews.
These models are typically used with the `output_pydantic` parameter in CrewAI Tasks.
"""

from pydantic import BaseModel, Field
from typing import Optional

class SummarizerTaskOutput(BaseModel):
    """Pydantic model for the output of the summarization task."""
    summary_text: str = Field(..., description="The single string summary generated by the summarization agent.")
    # Potentially add other fields if the LLM tool or agent might return them structured,
    # e.g., image_references_made: Optional[List[str]] = None
    # For now, keeping it simple to just the summary string as per the plan.

# Add other task-specific output models here as needed.

class TitleGenerationOutput(BaseModel):
    """Pydantic model for the output of the title generation task."""
    suggested_title: str = Field(..., description="The AI-generated title for the content, or an error message.") 